---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: comfyui
      app.kubernetes.io/instance: comfyui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: comfyui
        app.kubernetes.io/instance: comfyui
    spec:
      runtimeClassName: nvidia
      imagePullSecrets:
        - name: registry-mon-lab-lan-secret
      serviceAccountName: comfyui
      securityContext: {}
      containers:
        - name: comfyui
          image: "harbor.mon-lab.lan/gpu/comfyui:0.3.66"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8848
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: comfyui-storage
              mountPath: /home/workspace/ComfyUI/custom_nodes
              subPath: custom-nodes
            - name: comfyui-model-storage
              mountPath: /home/workspace/ComfyUI/models
              subPath: models
            - name: comfyui-storage
              mountPath: /home/workspace/ComfyUI/input
              subPath: input
            - name: comfyui-storage
              mountPath: /home/workspace/ComfyUI/output
              subPath: output
            - name: comfyui-storage
              mountPath: /home/workspace/ComfyUI/user
              subPath: user
            - name: comfyui-storage
              mountPath: /home/workspace/ComfyUI/temp
              subPath: temp
      volumes:
        - name: comfyui-storage
          persistentVolumeClaim:
            claimName: comfyui-pvc
        - name: comfyui-model-storage
          persistentVolumeClaim:
            claimName: comfyui-model-pvc
