---
# Source: comfyui/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfyui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: comfyui-comfyui-helm
    meta.helm.sh/release-namespace: "comfyui"
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50g"
spec:
  ingressClassName: nginx
  rules:
    - host: comfyui.mon-lab.lan
      http:
        paths:
          - backend:
              service:
                name: comfyui
                port:
                  number: 80
            path: /
            pathType: Prefix
