---
# Source: comfyui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: comfyui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: comfyui-comfyui-helm
    meta.helm.sh/release-namespace: "comfyui"
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: {{ .Values.nodePort }}
      targetPort: 8848
  selector:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
